apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name:  demo
          image: lowtechturtle/turtlek8senv:secretfile
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /secrets/
            name: demo-secret-volume
            readOnly: true
      volumes:
      - name: demo-secret-volume
        secret:
          secretName: turtle-secret
